name: SpeedChangerClock
version: '${project.version}'
main: in.masem.speedchangerclock.SpeedChangerClock
api-version: 1.19

commands:
  speedclock:
    usage: /<command>
    description: gives the player a custom speed.
    aliases: [ sp, spdclk, sck ]